-- Migration 005: static town/city locations for Gen 3 games.
-- These locations have no wild Pokémon encounter areas so PokeAPI never seeds
-- them automatically.  Negative IDs are used to guarantee no collision with
-- positive PokeAPI location-area IDs.  Friendly display names (Title Case with
-- spaces) keep them visually distinct from the slug-format PokeAPI entries.

-- ── Kanto (FireRed = version 10, LeafGreen = version 11) ────────────────────
INSERT OR IGNORE INTO location (id, name, version_id, region) VALUES
  (-1,  'Pallet Town',    10, 'kanto'),
  (-2,  'Viridian City',  10, 'kanto'),
  (-3,  'Pewter City',    10, 'kanto'),
  (-4,  'Cerulean City',  10, 'kanto'),
  (-5,  'Vermilion City', 10, 'kanto'),
  (-6,  'Lavender Town',  10, 'kanto'),
  (-7,  'Celadon City',   10, 'kanto'),
  (-8,  'Fuchsia City',   10, 'kanto'),
  (-9,  'Saffron City',   10, 'kanto'),
  (-10, 'Cinnabar Island',10, 'kanto'),
  (-11, 'One Island',     10, 'kanto'),
  (-12, 'Two Island',     10, 'kanto'),
  (-13, 'Three Island',   10, 'kanto'),
  (-14, 'Four Island',    10, 'kanto'),
  (-15, 'Five Island',    10, 'kanto'),
  (-16, 'Six Island',     10, 'kanto'),
  (-17, 'Seven Island',   10, 'kanto'),
  (-18, 'Pallet Town',    11, 'kanto'),
  (-19, 'Viridian City',  11, 'kanto'),
  (-20, 'Pewter City',    11, 'kanto'),
  (-21, 'Cerulean City',  11, 'kanto'),
  (-22, 'Vermilion City', 11, 'kanto'),
  (-23, 'Lavender Town',  11, 'kanto'),
  (-24, 'Celadon City',   11, 'kanto'),
  (-25, 'Fuchsia City',   11, 'kanto'),
  (-26, 'Saffron City',   11, 'kanto'),
  (-27, 'Cinnabar Island',11, 'kanto'),
  (-28, 'One Island',     11, 'kanto'),
  (-29, 'Two Island',     11, 'kanto'),
  (-30, 'Three Island',   11, 'kanto'),
  (-31, 'Four Island',    11, 'kanto'),
  (-32, 'Five Island',    11, 'kanto'),
  (-33, 'Six Island',     11, 'kanto'),
  (-34, 'Seven Island',   11, 'kanto');

-- ── Hoenn (Ruby = 6, Sapphire = 7, Emerald = 8) ─────────────────────────────
INSERT OR IGNORE INTO location (id, name, version_id, region) VALUES
  (-35, 'Littleroot Town', 6, 'hoenn'),
  (-36, 'Oldale Town',     6, 'hoenn'),
  (-37, 'Petalburg City',  6, 'hoenn'),
  (-38, 'Rustboro City',   6, 'hoenn'),
  (-39, 'Dewford Town',    6, 'hoenn'),
  (-40, 'Slateport City',  6, 'hoenn'),
  (-41, 'Mauville City',   6, 'hoenn'),
  (-42, 'Verdanturf Town', 6, 'hoenn'),
  (-43, 'Fallarbor Town',  6, 'hoenn'),
  (-44, 'Lavaridge Town',  6, 'hoenn'),
  (-45, 'Fortree City',    6, 'hoenn'),
  (-46, 'Lilycove City',   6, 'hoenn'),
  (-47, 'Mossdeep City',   6, 'hoenn'),
  (-48, 'Sootopolis City', 6, 'hoenn'),
  (-49, 'Ever Grande City',6, 'hoenn'),
  (-50, 'Pacifidlog Town', 6, 'hoenn'),
  (-51, 'Littleroot Town', 7, 'hoenn'),
  (-52, 'Oldale Town',     7, 'hoenn'),
  (-53, 'Petalburg City',  7, 'hoenn'),
  (-54, 'Rustboro City',   7, 'hoenn'),
  (-55, 'Dewford Town',    7, 'hoenn'),
  (-56, 'Slateport City',  7, 'hoenn'),
  (-57, 'Mauville City',   7, 'hoenn'),
  (-58, 'Verdanturf Town', 7, 'hoenn'),
  (-59, 'Fallarbor Town',  7, 'hoenn'),
  (-60, 'Lavaridge Town',  7, 'hoenn'),
  (-61, 'Fortree City',    7, 'hoenn'),
  (-62, 'Lilycove City',   7, 'hoenn'),
  (-63, 'Mossdeep City',   7, 'hoenn'),
  (-64, 'Sootopolis City', 7, 'hoenn'),
  (-65, 'Ever Grande City',7, 'hoenn'),
  (-66, 'Pacifidlog Town', 7, 'hoenn'),
  (-67, 'Littleroot Town', 8, 'hoenn'),
  (-68, 'Oldale Town',     8, 'hoenn'),
  (-69, 'Petalburg City',  8, 'hoenn'),
  (-70, 'Rustboro City',   8, 'hoenn'),
  (-71, 'Dewford Town',    8, 'hoenn'),
  (-72, 'Slateport City',  8, 'hoenn'),
  (-73, 'Mauville City',   8, 'hoenn'),
  (-74, 'Verdanturf Town', 8, 'hoenn'),
  (-75, 'Fallarbor Town',  8, 'hoenn'),
  (-76, 'Lavaridge Town',  8, 'hoenn'),
  (-77, 'Fortree City',    8, 'hoenn'),
  (-78, 'Lilycove City',   8, 'hoenn'),
  (-79, 'Mossdeep City',   8, 'hoenn'),
  (-80, 'Sootopolis City', 8, 'hoenn'),
  (-81, 'Ever Grande City',8, 'hoenn'),
  (-82, 'Pacifidlog Town', 8, 'hoenn');
