-- 007_tm_moves.sql
-- Maps TM numbers to move names.
-- Gen 3 uses the same 50 TMs across Ruby/Sapphire (vg 5), Emerald (vg 6),
-- and FireRed/LeafGreen (vg 7), so no version-group column is needed.

CREATE TABLE IF NOT EXISTS tm_move (
    tm_number INTEGER PRIMARY KEY,
    move_name TEXT NOT NULL
);

INSERT OR IGNORE INTO tm_move VALUES
    (1,  'focus-punch'),
    (2,  'dragon-claw'),
    (3,  'water-pulse'),
    (4,  'calm-mind'),
    (5,  'roar'),
    (6,  'toxic'),
    (7,  'hail'),
    (8,  'bulk-up'),
    (9,  'bullet-seed'),
    (10, 'hidden-power'),
    (11, 'sunny-day'),
    (12, 'taunt'),
    (13, 'ice-beam'),
    (14, 'blizzard'),
    (15, 'hyper-beam'),
    (16, 'light-screen'),
    (17, 'protect'),
    (18, 'rain-dance'),
    (19, 'giga-drain'),
    (20, 'safeguard'),
    (21, 'frustration'),
    (22, 'solar-beam'),
    (23, 'iron-tail'),
    (24, 'thunderbolt'),
    (25, 'thunder'),
    (26, 'earthquake'),
    (27, 'return'),
    (28, 'dig'),
    (29, 'psychic'),
    (30, 'shadow-ball'),
    (31, 'brick-break'),
    (32, 'double-team'),
    (33, 'reflect'),
    (34, 'shock-wave'),
    (35, 'flamethrower'),
    (36, 'sludge-bomb'),
    (37, 'sandstorm'),
    (38, 'fire-blast'),
    (39, 'rock-tomb'),
    (40, 'aerial-ace'),
    (41, 'torment'),
    (42, 'facade'),
    (43, 'secret-power'),
    (44, 'rest'),
    (45, 'attract'),
    (46, 'thief'),
    (47, 'steel-wing'),
    (48, 'skill-swap'),
    (49, 'snatch'),
    (50, 'overheat');
