// Package data embeds the bundled reference data seeds file.
// This is used as a fallback when no seeds.sql file exists adjacent to the
// database — e.g. on a brand-new Docker volume where PokeAPI has not yet been
// fetched.  Once EnsureAllEncounters completes, ExportSeeds writes a fresh
// seeds.sql next to the DB that supersedes this bundled copy on next restart.
package data

import _ "embed"

// SeedsSQL is the bundled INSERT OR IGNORE reference data generated by
// ExportSeeds after a previous full hydration run.
//
//go:embed seeds.sql
var SeedsSQL []byte
