package db

import (
	"database/sql"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// seedsTables is the ordered list of PokeAPI-sourced reference tables to
// export/import.  Order is FK-safe: parents always precede children.
var seedsTables = []string{
	"game_version",
	"pokemon_species",
	"pokemon_form",
	"move",
	"item",
	"location",
	"encounter",
	"learnset_entry",
	"item_availability",
	"evolution_condition",
	"api_cache_log",
}

// SeedsPath returns the path to the seeds SQL file adjacent to the DB file.
func SeedsPath(dbPath string) string {
	return filepath.Join(filepath.Dir(dbPath), "seeds.sql")
}

// ExportSeeds dumps all reference table rows as SQL INSERT statements to a
// seeds.sql file next to the database.  Overwrites any prior file.
// Safe to call repeatedly — results are always idempotent INSERT OR IGNORE.
func ExportSeeds(db *sql.DB, dbPath string) error {
	var sb strings.Builder
	sb.WriteString("-- PokemonProfessor reference data seeds\n")
	sb.WriteString("-- Auto-generated by ExportSeeds. Do not edit manually.\n")
	sb.WriteString("PRAGMA foreign_keys = OFF;\n\n")

	for _, table := range seedsTables {
		if err := appendTableInserts(db, &sb, table); err != nil {
			return fmt.Errorf("export table %s: %w", table, err)
		}
	}

	sb.WriteString("PRAGMA foreign_keys = ON;\n")
	return os.WriteFile(SeedsPath(dbPath), []byte(sb.String()), 0644)
}

// ApplySeedsIfEmpty loads reference data into the database when the location
// table is empty.
// SEC-014: By default, only the embedded bundled seeds are used. The
// filesystem seeds.sql file adjacent to the DB is only read if the
// POKEMON_TRUST_FS_SEEDS=1 environment variable is explicitly set.
func ApplySeedsIfEmpty(db *sql.DB, dbPath string, bundled []byte) error {
	var count int
	if err := db.QueryRow(`SELECT COUNT(*) FROM location`).Scan(&count); err != nil || count > 0 {
		return nil // table missing (pre-migration) or already populated
	}

	var data []byte
	if os.Getenv("POKEMON_TRUST_FS_SEEDS") == "1" {
		fsData, err := os.ReadFile(SeedsPath(dbPath))
		if err == nil {
			log.Printf("seeds: using filesystem seeds file (POKEMON_TRUST_FS_SEEDS=1)")
			data = fsData
		}
	}

	if data == nil {
		if len(bundled) == 0 {
			return nil // no seeds anywhere — PokeAPI will hydrate lazily
		}
		data = bundled // use the copy embedded in the binary
	}

	// Execute each semicolon-terminated statement individually.
	// The auto-generated file places exactly one statement per line ending in ";\n".
	for _, stmt := range strings.Split(string(data), ";\n") {
		s := strings.TrimSpace(stmt)
		if s == "" || strings.HasPrefix(s, "--") {
			continue
		}
		if _, err := db.Exec(s); err != nil {
			return fmt.Errorf("apply seeds stmt %q: %w", truncate(s, 60), err)
		}
	}
	return nil
}

// ─── helpers ──────────────────────────────────────────────────────────────────

// validTableName matches only lowercase-alpha-underscore table names.
// SEC-004: appendTableInserts uses string interpolation for the table name
// because SQL placeholders cannot be used for identifiers. This regex
// allowlist ensures only known safe names are accepted.
var validTableName = regexp.MustCompile(`^[a-z_]+$`)

func appendTableInserts(db *sql.DB, sb *strings.Builder, table string) error {
	if !validTableName.MatchString(table) {
		return fmt.Errorf("invalid table name: %q", table)
	}
	rows, err := db.Query("SELECT * FROM " + table) //nolint:gosec — table validated above
	if err != nil {
		return err
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return err
	}
	if len(cols) == 0 {
		return nil
	}

	count := 0
	fmt.Fprintf(sb, "-- Table: %s\n", table)
	for rows.Next() {
		vals := make([]interface{}, len(cols))
		ptrs := make([]interface{}, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return err
		}
		fmt.Fprintf(sb, "INSERT OR IGNORE INTO %s VALUES (", table)
		for i, v := range vals {
			if i > 0 {
				sb.WriteString(", ")
			}
			writeSQLLiteral(sb, v)
		}
		sb.WriteString(");\n")
		count++
	}
	fmt.Fprintf(sb, "-- %d rows\n\n", count)
	return rows.Err()
}

func writeSQLLiteral(sb *strings.Builder, v interface{}) {
	switch t := v.(type) {
	case nil:
		sb.WriteString("NULL")
	case int64:
		fmt.Fprintf(sb, "%d", t)
	case float64:
		fmt.Fprintf(sb, "%g", t)
	case string:
		sb.WriteByte('\'')
		sb.WriteString(strings.ReplaceAll(t, "'", "''"))
		sb.WriteByte('\'')
	case []byte:
		sb.WriteByte('\'')
		sb.WriteString(strings.ReplaceAll(string(t), "'", "''"))
		sb.WriteByte('\'')
	default:
		sb.WriteByte('\'')
		fmt.Fprintf(sb, "%v", t)
		sb.WriteByte('\'')
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}
